# This is a basic workflow to help you get started with Actions

name: Terraform-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ '*' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform CI
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@main

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1
        
      - name: Install Inspec 
        uses: actionshub/chef-install@1.1.0


      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init Basic
        id: init
        run: | 
          cd tests/basic
          terraform init

      - name: Terraform Plan Basic
        id: plan
        run: | 
          export ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}
          export ARM_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}
          export ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}
          export ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}
          cd tests/basic
          terraform plan
          
      - name: Terraform Apply Basic
        id: apply
        run: | 
          export ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}
          export ARM_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}
          export ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}
          export ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}
          cd tests/basic
          terraform apply --auto-approve

      - name: Inspec Scan Basic
        run: | 
          export AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}
          export AZURE_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}
          export AZURE_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}
          export AZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}
          pwd
          inspec exec inspec/azure-inspec-tests --chef-license accept -t azure://
        continue-on-error: true

      - name: Terraform Destroy Basic
        id: destroy
        run: | 
          export ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}
          export ARM_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}
          export ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}
          export ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}
          cd tests/basic
          terraform destroy --auto-approve


